#!/bin/bash

# BookMart Export Script
echo "📚 BookMart Website Export"
echo "========================="
echo ""
echo "Your complete bookstore website is ready!"
echo ""
echo "What's included:"
echo "✓ Full-featured bookstore with grade filtering"
echo "✓ Shopping cart and checkout system"
echo "✓ Email notifications to erikselimi205@gmail.com"
echo "✓ Admin panel to manage books and prices"
echo "✓ Mobile-responsive design"
echo ""
echo "Deployment options:"
echo "1. Vercel.com (recommended, free)"
echo "2. Netlify.com (free)"
echo "3. Railway.app (free tier)"
echo ""
echo "Admin panel will be available at: yoursite.com/admin"
echo ""
echo "See DEPLOYMENT_GUIDE.md for complete instructions!"
echo ""
echo "Happy selling! 🚀"